# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *

import diplo


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 543)
        MainWindow.setMaximumSize(QtCore.QSize(724, 543))
        MainWindow.setStyleSheet("background-color: rgb(252, 175, 62);\n""image: url(:/diplo/ENSAI.png);")
        MainWindow.setProperty("Date", QtCore.QDate(2020, 6, 10))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonTransport = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTransport.setGeometry(QtCore.QRect(290, 410, 141, 50))
        self.pushButtonTransport.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButtonTransport.setStyleSheet("height: 3em")
        self.pushButtonTransport.setObjectName("pushButtonTransport")
        self.pushButtonAffectation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAffectation.setGeometry(QtCore.QRect(20, 410, 141, 50))
        self.pushButtonAffectation.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButtonAffectation.setStyleSheet("height: 3em")
        self.pushButtonAffectation.setObjectName("pushButtonAffectation")
        self.pushButtonSimplex = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSimplex.setGeometry(QtCore.QRect(560, 410, 131, 50))
        self.pushButtonSimplex.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButtonSimplex.setStyleSheet("height: 3em")
        self.pushButtonSimplex.setObjectName("pushButtonSimplex")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonTransport.setText(_translate("MainWindow", " Transport"))
        self.pushButtonAffectation.setText(_translate("MainWindow", "Affectation"))
        self.pushButtonSimplex.setText(_translate("MainWindow", " Simplex"))

